### PR TITLE
Content preview

### PR DESCRIPTION
**Pull request by stevenzeiler**
This feature set enables in-line content preview for a significant set of BitcoinFiles types including:

- plain text
- markdown
- img
- video
- audio
- pdf

### CODE REVIEW

**Comment by attilaaf** [comment]
height limit

@stevenzeiler Can you please put a max height on the image so it does not overflow on desktop or mobile? Thanks!

**Comment by attilaaf** [comment]
pdf ideas

@DanielKrawisz @coinyeezy @rxxndy @stevenzeiler  Any ideas on what we can do with pdf's easily?

**Comment by attilaaf** [comment]
shownothing

+ this one please @stevenzeiler

**Comment by attilaaf** [comment]
I also noticed this exception...is this a problem?

```
$ npm run dev

> boostpow-publish@1.0.5 dev /Users/sauron/git/me/boostpow-publish
> next dev -p 4000

[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:4000 ...
[ ready ] compiled successfully - ready on http://localhost:4000
[ event ] build page: /
[ wait ]  compiling ...
[ ready ] compiled successfully - ready on http://localhost:4000
Warning: A component contains an input of type text with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://fb.me/react-controlled-components
    in input (at payment-popup/index.js:233)
    in div (at payment-popup/index.js:222)
    in form (at payment-popup/index.js:221)
    in div (at payment-popup/index.js:220)
    in div (at payment-popup/index.js:205)
    in div (at payment-popup/index.js:203)
    in div (at payment-popup/index.js:202)
    in PaymentPopup (at pages/index.js:60)
    in main (at pages/index.js:59)
    in div (at pages/index.js:53)
    in Home
    in App
    in Unknown
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in AppContainer
```

**Comment by stevenzeiler** [comment]
> height limit
> 
> @stevenzeiler Can you please put a max height on the image so it does not overflow on desktop or mobile? Thanks!

Images do have a max height on mobile already, I can put one on desktop sizes as well.

**Comment by stevenzeiler** [comment]
> I also noticed this warning exception...is this a problem?
> 
> ```
> $ npm run dev
> 
> > boostpow-publish@1.0.5 dev /Users/sauron/git/me/boostpow-publish
> > next dev -p 4000
> 
> [ wait ]  starting the development server ...
> [ info ]  waiting on http://localhost:4000 ...
> [ ready ] compiled successfully - ready on http://localhost:4000
> [ event ] build page: /
> [ wait ]  compiling ...
> [ ready ] compiled successfully - ready on http://localhost:4000
> Warning: A component contains an input of type text with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://fb.me/react-controlled-components
>     in input (at payment-popup/index.js:233)
>     in div (at payment-popup/index.js:222)
>     in form (at payment-popup/index.js:221)
>     in div (at payment-popup/index.js:220)
>     in div (at payment-popup/index.js:205)
>     in div (at payment-popup/index.js:203)
>     in div (at payment-popup/index.js:202)
>     in PaymentPopup (at pages/index.js:60)
>     in main (at pages/index.js:59)
>     in div (at pages/index.js:53)
>     in Home
>     in App
>     in Unknown
>     in Context.Provider
>     in Context.Provider
>     in Context.Provider
>     in AppContainer
> ```

Not sure if this was already there when I started, but I think I may have a solution.

**Comment by stevenzeiler** [comment]
> shownothing
> 
> * this one please @stevenzeiler

Yes we can show nothing if it is invalid I will do that.

**Comment by stevenzeiler** [comment]
> > I also noticed this warning exception...is this a problem?
> > ```
> > $ npm run dev
> > 
> > > boostpow-publish@1.0.5 dev /Users/sauron/git/me/boostpow-publish
> > > next dev -p 4000
> > 
> > [ wait ]  starting the development server ...
> > [ info ]  waiting on http://localhost:4000 ...
> > [ ready ] compiled successfully - ready on http://localhost:4000
> > [ event ] build page: /
> > [ wait ]  compiling ...
> > [ ready ] compiled successfully - ready on http://localhost:4000
> > Warning: A component contains an input of type text with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://fb.me/react-controlled-components
> >     in input (at payment-popup/index.js:233)
> >     in div (at payment-popup/index.js:222)
> >     in form (at payment-popup/index.js:221)
> >     in div (at payment-popup/index.js:220)
> >     in div (at payment-popup/index.js:205)
> >     in div (at payment-popup/index.js:203)
> >     in div (at payment-popup/index.js:202)
> >     in PaymentPopup (at pages/index.js:60)
> >     in main (at pages/index.js:59)
> >     in div (at pages/index.js:53)
> >     in Home
> >     in App
> >     in Unknown
> >     in Context.Provider
> >     in Context.Provider
> >     in Context.Provider
> >     in AppContainer
> > ```
> 
> Not sure if this was already there when I started, but I think I may have a solution.

This issue is resolved now.

**Comment by stevenzeiler** [comment]
> > shownothing
> > 
> > * this one please @stevenzeiler
> 
> Yes we can show nothing if it is invalid I will do that.

This issue is resolved, it now displays no preview for content not found on the server

**Comment by stevenzeiler** [comment]
> > height limit
> > @stevenzeiler Can you please put a max height on the image so it does not overflow on desktop or mobile? Thanks!
> 
> Images do have a max height on mobile already, I can put one on desktop sizes as well.

I limited the image height to 200px on desktop and 100px on mobile, should be resolved now.

**Comment by stevenzeiler** [comment]
> pdf ideas
> 
> @DanielKrawisz @coinyeezy @rxxndy @stevenzeiler Any ideas on what we can do with pdf's easily?

I limited the width of the PDF preview so that it displays more of the height.

**Pull request merged**
